# Generated by Django 3.1.5 on 2022-03-21 03:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='admin@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='feeddatamodel',
            name='timing',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 21, 3, 31, 18, 105184, tzinfo=utc)),
        ),
    ]
