# Generated by Django 3.1.5 on 2022-03-20 16:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeddatamodel',
            name='attendies',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feeddatamodel',
            name='timing',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 20, 16, 47, 53, 604438, tzinfo=utc)),
        ),
    ]
